CREATE DATABASE [UNIVALI_CSHARP]
GO
USE [UNIVALI_CSHARP]
GO
CREATE TABLE [dbo].[Grupo](
[Id] [int] IDENTITY(1,1) NOT NULL,
[Nome] [nvarchar](50) NULL,
CONSTRAINT [PK_Grupo] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GO
CREATE TABLE [dbo].[Produto](
[Id] [int] IDENTITY(1,1) NOT NULL,
[Nome] [nvarchar](100) NULL,
[IdGrupo] [int] NOT NULL,
[Custo] [decimal](17, 2) NULL,
[Venda] [decimal](17, 2) NULL,
[Saldo] [int] NULL,
CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Produto] WITH CHECK ADD CONSTRAINT [FK_Produto_Grupo] FOREIGN KEY([IdGrupo])
REFERENCES [dbo].[Grupo] ([Id])
GO
ALTER TABLE [dbo].[Produto] CHECK CONSTRAINT [FK_Produto_Grupo]
GO